# Generated by Django 3.2.9 on 2022-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sniper', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nftattribute',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'value'), name='unique appversion'),
        ),
    ]
